name: Deploy Flet App to GitHub Pages

on:
  push:
    branches:
      - main  # mainブランチにPushされた時に実行

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version" # 管理ファイルに合わせる

      - name: Install dependencies
        run: |
          uv sync

      - name: Flet Publish
        run: |
          uv run flet publish ./main.py --base-url /feti-battler/ --web-renderer canvaskit

          # ビルド成果物のディレクトリ名をappに変更し、LPをルートに配置する準備
          mv dist app
          mkdir dist
          mv app dist/
          # ルートのLP用index.htmlをdistの直下にコピー
          cp index.html dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
